name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  lint-test:
    name: lint, type-check, test (py${{ matrix.python }} on ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.12", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup uv and Python
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Sync dependencies (dev group)
        run: uv sync --group dev

      - name: Show versions
        run: |
          uv --version
          uv run python -V
          uv run pytest --version
          uv run ruff --version
          uv run mypy --version

      - name: Lint (ruff, black, isort)
        run: |
          uv run ruff check kcmt tests
          uv run black --check kcmt tests
          uv run isort --check-only kcmt tests

      - name: Type check (mypy)
        run: uv run mypy kcmt

      - name: Run tests (warnings as errors, parallel, coverage)
        env:
          OPENAI_API_KEY: sk-test
          GITHUB_TOKEN: ghp_test
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
        run: |
          uv run pytest -n auto -ra -vv \
            -W default -W error::DeprecationWarning -W error::ResourceWarning \
            --strict-config --strict-markers \
            --cov=kcmt --cov-branch \
            --cov-report=term-missing:skip-covered \
            --cov-fail-under=85 tests